googlefonts/diffenator2

src/diffenator/shape.py

If we're going to filter out a bunch of words based on the contents of buffer B, do the filtering first before bothering to shape buffer A.

Silly optimization which saves 33%

---

src/diffenator/__init__.py
src/diffenator/__main__.py
src/diffenator/utils.py
tests/data/ninja_files/diff-filter-styles.txt
tests/data/ninja_files/diff-imgs.txt
tests/data/ninja_files/diff-standard.txt
tests/test_ninja.py

In Diffbrowsers, I only allowed four font styles per page since browserstack put restrictions on image height. Even though we can generate images which are much higher, it's still worthwhile only allowing a max of four styles per page. Generating huge images can cause github runners to crash.

Only allow four styles max per page

---

src/diffenator2/renderer.py
src/diffenator2/shape.py

This fixes a variety of rendering issues, particularly with mark-positioned glyphs.
Before:
After:
- Don't die on empty words
- Just use cairo for everything, for now
- Drop all the hb scaling

Rendering fixes

---

.github/workflows/publish-release.yml
pyproject.toml

This PR finally adds the ability to publish a release to pypi. Dynamic versioning is handled by the fab plugin, https://github.com/tiangolo/poetry-version-plugin. 
Still testing this at the moment so releases are being pushed to the pypi test area. If I'm happy with it, I'll send em to prod.

CI: add publish_release

---

src/diffenator2/font.py

fontTools.ttLib.scale_upem takes a new UPEM value:
```
def scale_upem(font, new_upem):
```
But we feed it a ratio:
```
ratio = new_font.ttFont["head"].unitsPerEm / old_font.ttFont["head"].unitsPerEm
if ratio != 1.0:
scale_upem(old_font.ttFont, ratio)
```
This means that old_font's UPEM generally ends up around zero, and everything goes wrong afterwards.
Found while debugging something else...

scale_upem takes a new upem

---

src/diffenator2/renderer.py

Diffenator was giving false negatives and false positives when comparing fonts with different vertical metrics. This is because the renderered images had different baselines, and when we subtracted one from the other, we got 'ghosting'.
This uses harfbuzz to get font extents (because HB applies MVAR variations for us), making the baselines line up.

Use font metrics when renderering

---

src/diffenator2/renderer.py

I was getting crashes with some regression tests; if a glyph hangs over to the left, we want to maintain the negative X coordinate, or else the right edge can be less than the left edge, and that makes Skia crash.

Fix crash with left-hanging glyphs

---

src/diffenator2/renderer.py

We have this hidden renderer tester in `python3 -m diffenator.renderer` where you can use the renderer to turn a string into a PNG file. I recently had to use this to test a variable font and found I couldn't set variation properties on it. Now I can.

Allowing passing variations to the renderer tester

---

src/diffenator2/renderer.py

I noticed diffenator2 is failing in https://github.com/google/fonts/actions/runs/4416701337/jobs/7742863066#step:6:2394. It's failing because Skia is attempting to create a canvas by using an incorrectly defined bounding box variable. Bounds are defined as a tuple `(xMin, yMin, xMax, yMax)`. Currently, our bounds tuple could have negative xMax or yMax values which isn't correct (you occasionally get negative values for glyphs such as combining marks).

render: calculate canvas bounds correctly

---

src/diffenator2/templates/CSSFontStyle.partial.html
src/diffenator2/templates/_base.html

Fixes #40, and makes missing glyphs more obvious:

Use adobe notdef

---

README.md
src/diffenator2/__init__.py
src/diffenator2/__main__.py
src/diffenator2/_diffbrowsers.py
src/diffenator2/_diffenator.py
src/diffenator2/html.py
src/diffenator2/templates/diffbrowsers_glyphs.html
src/diffenator2/utils.py
tests/data/ninja_files/diff-filter-styles.txt
tests/data/ninja_files/diff-imgs.txt
tests/data/ninja_files/diff-standard.txt
tests/data/ninja_files/diff-threshold.txt
tests/data/ninja_files/proof-filter-styles.txt
tests/data/ninja_files/proof-imgs.txt
tests/data/ninja_files/proof-standard.txt
tests/test_functional.py
tests/test_utils.py

This PR allows you to filter which glyphs you want to see. Simply supply a regex string for the glyps you want to see e.g
`diffenator2 proof font1.ttf --glyphs "[!-~]"`
Above example will only check the ascii set.

Glyph filtering

---

src/diffenator2/font.py

Currently we call `DFont()` on all the fonts both in the "orchestration" command (diffenator2) and also the ninja command (_diffbrowsers). Whenever we initialise a `DFont` object, we run `self.jFont = jfont.TTJ(self.ttFont)` to decompile the font into a JSON representation. This takes quite a lot of time, and `diffenator2` doesn't even use that information! If you're running `diffenator2 proof` (which doesn't use the TTJ object either), then you decompile the font *twice* for no benefit.
Before this PR:
```
% time diffenator2 proof fonts/NotoSansMono/unhinted/ttf/NotoSansMono-*
diffenator2 proof   48.72s user 1.32s system 99% cpu 50.288 total
```
After this PR:
```
% time diffenator2 proof fonts/NotoSansMono/unhinted/ttf/NotoSansMono-*
diffenator2 proof   9.38s user 0.77s system 99% cpu …
```

Only compute the TTJ on demand

---

src/diffenator2/templates/_base.html
src/diffenator2/templates/diffbrowsers_waterfall.html

This PR implements an OpenType feature picker in the html views. This feature was requested by @vv-monsalve (great idea btw).
Since the text boxes are also contenteditable, it's becoming a very nice playground to test out custom user text, similar to Impallari's tester.

templates: Add opentype feature picker

---

src/diffenator2/templates/diffenator.html

We use the `node` class for all sorts of things. Without this patch, a diff of Noto Serif CJK failed because there were *millions* of nodes, most of which did not want a click handler attached.

Only add click handler to nodes in the difftable

---

src/diffenator2/__init__.py
src/diffenator2/__main__.py
src/diffenator2/_diffenator.py
src/diffenator2/shape.py
tests/data/ninja_files/diff-filter-styles.txt
tests/data/ninja_files/diff-imgs.txt
tests/data/ninja_files/diff-standard.txt
tests/data/ninja_files/diff-threshold.txt
tests/data/ninja_files/proof-filter-styles.txt
tests/test_ninja.py

This adds:
* A `--precision` option to change the font size used when creating the renders for diffing. 
* A `--no-tables` option to skip generating the JFont table diff.
* A `--no-words` option to skip using the wordlists and just diff glyphs.
Also I turned on "run black on save" so some files got reformatted but that's not a bad thing.

More options

---

pyproject.toml
src/diffenator2/templates/diffbrowsers_proofer.html

Currently, the proof is broken for views other than "line by line"

fix proof views

---

.github/workflows/test.yml
pyproject.toml
src/diffenator2/jfont.py
src/diffenator2/templates/_base.html

Paths nodes and components are now visible.

diff tables: make glyf table diffs human readable

---

src/diffenator2/jfont.py
src/diffenator2/templates/diffenator.html

This PR will only draw diff tree nodes which are visible. Currently, we create a DOM element for every node and then hide the invisible ones. Unfortunately, the current approach is very slow for fonts which have a lot of changes. This will speed things up significantly.
cc @simoncozens

diff tables: only draw nodes which are visible

---

README.md

Adding the paragraph option under User Wordlist

---

src/diffenator2/__init__.py
src/diffenator2/screenshot.py
src/diffenator2/utils.py

google/fonts and f-actions/diffenator are timing out on mac image generation. This PR solves the issue by creating gis from images with the same dimensions and dropping Safari img generation.

Fix github actions image generation

---

src/diffenator2/jfont.py

- Serialize old-school kern table
- black

Fix crash on kern table

---

.github/workflows/test.yml
pyproject.toml
src/diffenator2/jfont.py

https://github.com/fonttools/fonttools/pull/3395 introduces the variable components table (VARC) and deprecates the glyph table's `isVarComposite` method.

Upgrade fonttools

---

src/diffenator2/html.py
src/diffenator2/templates/CSSFontFace.partial.html

@madig Sorry for the delay
Fixes #148

html: escape font filenames
